name: NPM Release

on:
  push:
    branches: [master]

jobs:
  deploy_master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: npm ci

      - run: npm run changelog


