name: Node CI

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    strategy:
      matrix:
        node: [12, 14, 16]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run test
      - run: npm run build
